### ISSUE TITLE
Jvm does not start

### ISSUE THREAD

**Issue by haasechr** [KevinLawson/excel-cdk#11]
JVM does not initialize. Upon first try 

'Unexpected exception caught in CdkInterfaceDll - initJaceDll(): Assert failed: Unable to find the class, org.jace.util.ShutdownHook.' 

is thrown, afterwards

'Unexpected exception caught in CdkInterfaceDll - initJaceDll(): Unable to create the virtual machine. The error was -5'

Any suggestions?

Greetings

**Comment by KevinLawson** [comment]
Hi

I came across this one some time ago after a java upgrade. I solved it at
the time by adjusting and recompiling the JACE library which was causing
the problem. Best I can offer is to use the latest installer of LICSS:
https://github.com/KevinLawson/excel-cdk/releases/download/v3.3/LICSS-3.3.1-FullInstaller.exe
(which has the updated JACE dlls) and make sure you have up to date java
for the version of excel you are using. 64 bit for 64 bit office, 32 bit
for 32 bit office. Not having the correct java installed is often the cause
of initialisation errors.

I have just tested LICSS on Windows 10 with 64 bit Office 2013 and java
1.8.0_201 (64 bit) and it works fine.

Hope this helps - please let me know if this (or something else) works.

Kevin

**Comment by haasechr** [comment]
Hi,

I am stuck with a 2010 32bit Office on a Win10 machine. Both (32bit and 64bit) JAVA 1.8.0_201 installed.

The JACE dll in the lib64 dir dates to May 2016, while in the lib32 (which I need) to May 2012. 

Do you think this might the problem? Do see any chance to adjust the 32bit variant as well?  

Christian

**Comment by KevinLawson** [comment]
Hi Christian

I have just uploaded LICSS-3.3.2-FullInstaller.exe to GitHub which has the
correct updated Jace files for Java 8. I'm afraid I can't test it as I only
have Office 64 bit available. But please let me know if it works/doesn't
work for you.

Best wishes

Kevin
