### ISSUE TITLE
CDK interfaceDLL.dll not found

### ISSUE THREAD

**Issue by ezrabest** [KevinLawson/excel-cdk#12]
Hello, 
Thanks for the project, I have installed the files, 
and java 32+64
After running the excel file and Ctrl+E got the message structure enabling successful!
a new tab was created, but not an interactive tab.
BUT when I did CTRL+Shift+M I got the message "run-time error '53': file not found: cdkInterfaceDll.dll
I have tried to install all versions with similar results.
Thanks again

**Comment by KevinLawson** [comment]
Hi

Can you tell me what version of Windows you are using please and what
version of Excel (It looks like you have a 32 bit version from the
screenshot but this needs confirming). You should install the latest
version 3.3.2 (
https://github.com/KevinLawson/excel-cdk/releases/download/v3.3/LICSS-3.3.2-FullInstaller.exe).
Unfortunately, I haven't been able to test this on 32 bit Excel as yet
because I don't have a copy available but I'll see if I can find someone
who does and check all is well.

Btw: the fact that your tab is not interactive is to be expected - until
the <CTRL Shift M> structure enabling works it is not designed to be.

Best wishes

Kevin

**Comment by ezrabest** [comment]
Thank you very much for your quick response 
I’m using Office 365 account, version 1904, Excel 32 bit as you predicted.
My windows version is win10 home edition 64bit

I have installed LICSS on my previous computer with win10 pro 64 bit & Microsoft pro plus 2016 32bit as well, and the LICSS worked fine (I had only two days to test it and then changed computer). 
Is there anything I can do to assist and promote the fix?
Thanks again
Ezra

**Comment by ezrabest** [comment]
Thank youvery much for your quick response 

I’m usingOffice 365 account, version 1904, Excel 32 bit as you predicted.

My windowsversion is win10 home edition 64bit

 

I haveinstalled LICSS on my previous computer with win10 pro 64 bit & Microsoft proplus 2016 32bit as well, and the LICSS worked fine (I had only two days to testit and then changed computer). 

Is thereanything I can do to assist and promote the fix?

Thanksagain

BTW

during the installation,I noticed the following message

Kind regards, Ezra Ella 
    On Tuesday, May 7, 2019, 6:15:03 PM GMT+3, KevinLawson <notifications@github.com> wrote:  
 
 Hi

Can you tell me what version of Windows you are using please and what
version of Excel (It looks like you have a 32 bit version from the
screenshot but this needs confirming). You should install the latest
version 3.3.2 (
https://github.com/KevinLawson/excel-cdk/releases/download/v3.3/LICSS-3.3.2-FullInstaller.exe).
Unfortunately, I haven't been able to test this on 32 bit Excel as yet
because I don't have a copy available but I'll see if I can find someone
who does and check all is well.

Btw: the fact that your tab is not interactive is to be expected - until
the <CTRL Shift M> structure enabling works it is not designed to be.

Best wishes

Kevin

**Comment by ezrabest** [comment]
another thing: in the debugger, when I hover the mouse over the marked line       "mem = CDKGetFreeMemoryAvailable()"
The text mem=0 appear. 
Kind regards, Ezra
    On Tuesday, May 7, 2019, 6:15:03 PM GMT+3, KevinLawson <notifications@github.com> wrote:  
 
 Hi

Can you tell me what version of Windows you are using please and what
version of Excel (It looks like you have a 32 bit version from the
screenshot but this needs confirming). You should install the latest
version 3.3.2 (
https://github.com/KevinLawson/excel-cdk/releases/download/v3.3/LICSS-3.3.2-FullInstaller.exe).
Unfortunately, I haven't been able to test this on 32 bit Excel as yet
because I don't have a copy available but I'll see if I can find someone
who does and check all is well.

Btw: the fact that your tab is not interactive is to be expected - until
the <CTRL Shift M> structure enabling works it is not designed to be.

Best wishes

Kevin

**Comment by KevinLawson** [comment]
Hi

I have managed to replicate this problem with another user of Office 365
under Windows 10. LICSS 3.3.2 works fine with other versions of Excel (32
and 64 bit) so there doesn't appear to be a problem with the actual
program *per
se*. I think it is to do with the way Office 365 handles calls to DLLs.
That said, Sean Panton (see other user group postings) got things working
with Office 365 so it's may be not as simple as that. Best thing to try is
to copy the three DLLs: CdkInterfaceDll.dll, jace.dll and boost_thread.dll
from C:\Services\LICSS-3.3\lib32 to your SysWOW64 directory (usually
C:\Windows\SysWOW64; you will need admin privilege to do this). In the case
where I tried this, it cured the DLL calling problem but there was still an
initialisation error from JACE; see what happens for you and report back
please.

Best wishes

Kevin

**Comment by ezrabest** [comment]
Thank you very much KevinThe LICSS tab is now activeHowever, when pressing ctrl+shift+M I get the error:
"Failed to initialiseLICSS structure server

Unexpected exceptioncaught in CdkInterfaceDll- initJaceDll(): Assert failed: Unable to find theclass, org.jace.util.ShutdownHook"

Thanks, Ezra
    On Wednesday, May 8, 2019, 8:47:00 PM GMT+3, KevinLawson <notifications@github.com> wrote:  
 
 Hi

I have managed to replicate this problem with another user of Office 365
under Windows 10. LICSS 3.3.2 works fine with other versions of Excel (32
and 64 bit) so there doesn't appear to be a problem with the actual
program *per
se*. I think it is to do with the way Office 365 handles calls to DLLs.
That said, Sean Panton (see other user group postings) got things working
with Office 365 so it's may be not as simple as that. Best thing to try is
to copy the three DLLs: CdkInterfaceDll.dll, jace.dll and boost_thread.dll
from C:\Services\LICSS-3.3\lib32 to your SysWOW64 directory (usually
C:\Windows\SysWOW64; you will need admin privilege to do this). In the case
where I tried this, it cured the DLL calling problem but there was still an
initialisation error from JACE; see what happens for you and report back
please.

Best wishes

Kevin

**Comment by KevinLawson** [comment]
OK. If you now copy the 6 jar files in C:\Services\LICSS-3.3 into
C:\Windows (ie one level up from the SysWOW64 folder) I think it will all
work for you (again you will need admin permission to do this). This is
very far from ideal as one would wish to keep all the LICSS files away from
the system files. But Office 365 has new security features which appear to
stop external programs like this being called with any of the standard
methods (put the program directory in the user path, make the program
directory the current directory, etc). If anyone in the user group has come
up with a better solution I would be glad to hear of it.

Please let me know how you get on

Best wishes

Kevin

**Comment by ezrabest** [comment]
Thank you very much Kevin YOU ARE THE BEST!!!This solution works fine to me and now I can start learn LICSS features :)
Kind regards, Ezra
    On Friday, May 10, 2019, 1:05:26 PM GMT+3, KevinLawson <notifications@github.com> wrote:  
 
 OK. If you now copy the 6 jar files in C:\Services\LICSS-3.3 into
C:\Windows (ie one level up from the SysWOW64 folder) I think it will all
work for you (again you will need admin permission to do this). This is
very far from ideal as one would wish to keep all the LICSS files away from
the system files. But Office 365 has new security features which appear to
stop external programs like this being called with any of the standard
methods (put the program directory in the user path, make the program
directory the current directory, etc). If anyone in the user group has come
up with a better solution I would be glad to hear of it.

Please let me know how you get on

Best wishes

Kevin
