### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by plkx** [KevinLawson/excel-cdk#14]
Source code downloads (neither zip nor tar.gz) do not contain source code.

**Comment by KevinLawson** [comment]
LICSS-3.3.3-SourceCode.zip now added to project with java code for CDKInterfaceDll.jar and CDSSWin.jar. The VBA source code is in LICSSV3.3.xla. CDKIntefaceDll.jar and the corresponding dll are build using KRLBuildAll.bat which calls the Java compiler and the Windows SDK (v7.1). Build instructions are in the doc folder
