### ISSUE TITLE
Problems with new JAVA version 8u45

### ISSUE THREAD

**Issue by haasechr** [KevinLawson/excel-cdk#9]
Hi!

Thank you for this great tool! 

Unfortunately it seems to be incompatible with the latest JAVA version (8u45). I get the following message:

Failed to Initialise LICSS Structure Server:

Unexpected execption caught in CdkInterfaceDll - initJaceDll(); No default Sun JRE found

Cheers,
Christian

**Comment by KevinLawson** [comment]
Hi Christian

Thanks for your note. I don't think there is any problem with Java 8u45 per se as I am running this myself and LICSS works fine. Depending on whether you are running 32 bit or 64 bit MS Office you may need to install both 32 bit and 64 bit versions of Java to get LICSS to work. Specifically, the JACE component of LICSS uses a registry key to check which version of Java to use:

HKLM\SOFTWARE\JavaSoft\Java Runtime Environment\CurrentVersion.

For me, this is set to 1.8 in both the 32 bit and 64 bit parts of the system registry (see https://support.microsoft.com/en-us/kb/305097 for info on how to view the 32 bit registry keys)

Please try (re-)installing both 32 bit and 64 bit Java and let me know if this solves your problem.

Best wishes

Kevin

**Comment by haasechr** [comment]
Hi Kevin,

thanks for your incredible fast answer. You are right. After the last JAVA update only the 64 bit version was installed. My Office is 32 bit and after installing the 32 bit JAVA in addition everything works fine again.

Cheers,
Christian
